// This file contains accurate bordering data for LGAs across all Nigerian states

// Define the type for our borders data structure
export type LGABordersData = {
  [state: string]: {
    [lga: string]: string[] // Array of bordering LGAs
  }
}

// Comprehensive LGA bordering data for all Nigerian states
export const NIGERIA_LGA_BORDERS: LGABordersData = {
  // LAGOS STATE
  Lagos: {
    Agege: ["Alimosho", "Ifako-Ijaiye", "Ikeja", "Oshodi-Isolo"],
    "Ajeromi-Ifelodun": ["Amuwo-Odofin", "Apapa", "Surulere"],
    Alimosho: ["Agege", "Oshodi-Isolo", "Ifako-Ijaiye", "Ojo"],
    "Amuwo-Odofin": ["Ajeromi-Ifelodun", "Ojo", "Apapa"],
    Apapa: ["Ajeromi-Ifelodun", "Amuwo-Odofin", "Lagos Island", "Surulere"],
    Badagry: ["Ojo"],
    Epe: ["Ibeju-Lekki", "Ikorodu"],
    "Eti-Osa": ["Lagos Island", "Ibeju-Lekki"],
    "Ibeju-Lekki": ["Epe", "Eti-Osa"],
    "Ifako-Ijaiye": ["Agege", "Alimosho", "Ikeja"],
    Ikeja: ["Agege", "Ifako-Ijaiye", "Oshodi-Isolo", "Kosofe", "Shomolu"],
    Ikorodu: ["Kosofe", "Epe"],
    Kosofe: ["Ikeja", "Ikorodu", "Shomolu"],
    "Lagos Island": ["Apapa", "Eti-Osa", "Lagos Mainland"],
    "Lagos Mainland": ["Lagos Island", "Surulere", "Shomolu"],
    Mushin: ["Oshodi-Isolo", "Shomolu", "Surulere"],
    Ojo: ["Amuwo-Odofin", "Badagry", "Alimosho"],
    "Oshodi-Isolo": ["Agege", "Alimosho", "Ikeja", "Mushin", "Surulere"],
    Shomolu: ["Ikeja", "Kosofe", "Lagos Mainland", "Mushin"],
    Surulere: ["Ajeromi-Ifelodun", "Apapa", "Lagos Mainland", "Mushin", "Oshodi-Isolo"],
  },

  // ABIA STATE
  Abia: {
    "Aba North": ["Aba South", "Osisioma", "Obi Ngwa"],
    "Aba South": ["Aba North", "Osisioma", "Ugwunagbo"],
    Arochukwu: ["Ohafia", "Bende"],
    Bende: ["Arochukwu", "Ohafia", "Ikwuano", "Umuahia North", "Isiala Ngwa North"],
    Ikwuano: ["Bende", "Umuahia South", "Isiala Ngwa North"],
    "Isiala Ngwa North": ["Bende", "Ikwuano", "Isiala Ngwa South", "Osisioma"],
    "Isiala Ngwa South": ["Isiala Ngwa North", "Osisioma", "Obi Ngwa", "Ukwa East"],
    Isuikwuato: ["Umu Nneochi", "Ohafia"],
    "Obi Ngwa": ["Aba North", "Isiala Ngwa South", "Ugwunagbo", "Ukwa East"],
    Ohafia: ["Arochukwu", "Bende", "Isuikwuato"],
    Osisioma: ["Aba North", "Aba South", "Isiala Ngwa South", "Ugwunagbo"],
    Ugwunagbo: ["Aba South", "Osisioma", "Obi Ngwa", "Ukwa West"],
    "Ukwa East": ["Isiala Ngwa South", "Obi Ngwa", "Ukwa West"],
    "Ukwa West": ["Ugwunagbo", "Ukwa East"],
    "Umuahia North": ["Bende", "Umuahia South", "Ikwuano"],
    "Umuahia South": ["Umuahia North", "Ikwuano", "Isiala Ngwa North"],
    "Umu Nneochi": ["Isuikwuato"],
  },

  // ADAMAWA STATE
  Adamawa: {
    Demsa: ["Mayo Belwa", "Numan", "Lamurde"],
    Fufure: ["Yola South", "Song", "Girei"],
    Ganye: ["Toungo", "Jada", "Mayo Belwa"],
    Girei: ["Yola North", "Yola South", "Fufure", "Song"],
    Gombi: ["Hong", "Song"],
    Guyuk: ["Lamurde", "Shelleng"],
    Hong: ["Gombi", "Mubi South", "Song"],
    Jada: ["Ganye", "Mayo Belwa", "Toungo"],
    Lamurde: ["Demsa", "Numan", "Guyuk"],
    Madagali: ["Michika"],
    Maiha: ["Mubi North", "Mubi South"],
    "Mayo Belwa": ["Demsa", "Jada", "Ganye", "Yola South"],
    Michika: ["Madagali", "Mubi North"],
    "Mubi North": ["Michika", "Mubi South", "Maiha"],
    "Mubi South": ["Mubi North", "Hong", "Maiha"],
    Numan: ["Demsa", "Lamurde", "Shelleng"],
    Shelleng: ["Numan", "Guyuk", "Song"],
    Song: ["Girei", "Fufure", "Hong", "Gombi", "Shelleng"],
    Toungo: ["Ganye", "Jada"],
    "Yola North": ["Yola South", "Girei"],
    "Yola South": ["Yola North", "Girei", "Fufure", "Mayo Belwa"],
  },

  // AKWA IBOM STATE
  "Akwa Ibom": {
    Abak: ["Ukanafun", "Etim Ekpo", "Ikot Ekpene", "Essien Udim"],
    "Eastern Obolo": ["Ikot Abasi", "Mkpat-Enin"],
    Eket: ["Esit Eket", "Onna", "Nsit-Ubium"],
    "Esit Eket": ["Eket", "Ibeno"],
    "Essien Udim": ["Abak", "Ikot Ekpene", "Obot Akara"],
    "Etim Ekpo": ["Abak", "Ukanafun", "Ika"],
    Etinan: ["Nsit-Ibom", "Nsit-Ubium", "Onna"],
    Ibeno: ["Esit Eket", "Onna"],
    "Ibesikpo Asutan": ["Nsit-Ibom", "Nsit-Atai", "Uyo", "Uruan"],
    "Ibiono-Ibom": ["Itu", "Ikono", "Uyo"],
    Ika: ["Etim Ekpo", "Ukanafun"],
    Ikono: ["Ini", "Ibiono-Ibom", "Ikot Ekpene"],
    "Ikot Abasi": ["Eastern Obolo", "Mkpat-Enin", "Oruk Anam"],
    "Ikot Ekpene": ["Essien Udim", "Abak", "Obot Akara"],
    Ini: ["Ikono"],
    Itu: ["Ibiono-Ibom", "Uruan"],
    Mbo: ["Oron", "Okobo"],
    "Mkpat-Enin": ["Eastern Obolo", "Ikot Abasi", "Oruk Anam", "Onna"],
    "Nsit-Atai": ["Ibesikpo Asutan", "Nsit-Ibom", "Uruan", "Okobo"],
    "Nsit-Ibom": ["Ibesikpo Asutan", "Nsit-Atai", "Nsit-Ubium", "Etinan"],
    "Nsit-Ubium": ["Nsit-Ibom", "Etinan", "Onna", "Eket"],
    "Obot Akara": ["Essien Udim", "Ikot Ekpene"],
    Okobo: ["Nsit-Atai", "Uruan", "Oron", "Mbo", "Urue-Offong/Oruko"],
    Onna: ["Etinan", "Nsit-Ubium", "Eket", "Ibeno", "Mkpat-Enin"],
    Oron: ["Okobo", "Mbo", "Udung-Uko", "Urue-Offong/Oruko"],
    "Oruk Anam": ["Ikot Abasi", "Mkpat-Enin", "Ukanafun", "Abak"],
    "Udung-Uko": ["Oron", "Mbo"],
    Ukanafun: ["Abak", "Etim Ekpo", "Ika", "Oruk Anam"],
    Uruan: ["Ibesikpo Asutan", "Itu", "Nsit-Atai", "Okobo"],
    "Urue-Offong/Oruko": ["Okobo", "Oron"],
    Uyo: ["Ibesikpo Asutan", "Ibiono-Ibom", "Nsit-Ibom"],
  },

  // ANAMBRA STATE
  Anambra: {
    Aguata: ["Orumba North", "Orumba South", "Anaocha", "Nnewi South"],
    "Anambra East": ["Anambra West", "Oyi", "Ayamelum"],
    "Anambra West": ["Anambra East", "Ayamelum"],
    Anaocha: ["Aguata", "Njikoka", "Dunukofia", "Nnewi North"],
    "Awka North": ["Awka South", "Dunukofia", "Njikoka"],
    "Awka South": ["Awka North", "Njikoka", "Orumba North"],
    Ayamelum: ["Anambra East", "Anambra West", "Oyi"],
    Dunukofia: ["Anaocha", "Njikoka", "Oyi", "Awka North"],
    Ekwusigo: ["Nnewi North", "Ihiala", "Nnewi South"],
    "Idemili North": ["Idemili South", "Onitsha South", "Oyi"],
    "Idemili South": ["Idemili North", "Nnewi North", "Ihiala"],
    Ihiala: ["Ekwusigo", "Idemili South", "Nnewi South"],
    Njikoka: ["Anaocha", "Dunukofia", "Awka South", "Idemili North"],
    "Nnewi North": ["Nnewi South", "Ekwusigo", "Idemili South"],
    "Nnewi South": ["Nnewi North", "Ekwusigo", "Ihiala", "Aguata"],
    Ogbaru: ["Onitsha North", "Onitsha South", "Idemili North"],
    "Onitsha North": ["Onitsha South", "Ogbaru"],
    "Onitsha South": ["Onitsha North", "Ogbaru", "Idemili North"],
    "Orumba North": ["Orumba South", "Aguata", "Awka South"],
    "Orumba South": ["Orumba North", "Aguata"],
    Oyi: ["Anambra East", "Ayamelum", "Dunukofia", "Idemili North"],
  },

  // BAUCHI STATE
  Bauchi: {
    Alkaleri: ["Bauchi", "Kirfi", "Tafawa Balewa", "Toro"],
    Bauchi: ["Alkaleri", "Dass", "Toro"],
    Bogoro: ["Dass", "Tafawa Balewa"],
    Damban: ["Darazo", "Ganjuwa", "Jama'are"],
    Darazo: ["Damban", "Ganjuwa", "Misau", "Ningi"],
    Dass: ["Bauchi", "Bogoro", "Tafawa Balewa"],
    Gamawa: ["Jama'are", "Zaki"],
    Ganjuwa: ["Damban", "Darazo", "Ningi", "Toro"],
    Giade: ["Jama'are", "Katagum", "Shira"],
    "Itas/Gadau": ["Jama'are", "Katagum", "Shira", "Zaki"],
    "Jama'are": ["Damban", "Gamawa", "Giade", "Itas/Gadau", "Katagum"],
    Katagum: ["Giade", "Itas/Gadau", "Jama'are", "Zaki"],
    Kirfi: ["Alkaleri", "Bauchi"],
    Misau: ["Darazo", "Ningi", "Shira"],
    Ningi: ["Darazo", "Ganjuwa", "Misau", "Shira", "Warji"],
    Shira: ["Giade", "Itas/Gadau", "Misau", "Ningi"],
    "Tafawa Balewa": ["Alkaleri", "Bogoro", "Dass", "Toro"],
    Toro: ["Alkaleri", "Bauchi", "Ganjuwa", "Tafawa Balewa"],
    Warji: ["Ganjuwa", "Ningi"],
    Zaki: ["Gamawa", "Itas/Gadau", "Katagum"],
  },

  // BAYELSA STATE
  Bayelsa: {
    Brass: ["Nembe", "Southern Ijaw"],
    Ekeremor: ["Sagbama", "Southern Ijaw"],
    "Kolokuma/Opokuma": ["Yenagoa", "Southern Ijaw"],
    Nembe: ["Brass", "Ogbia", "Yenagoa"],
    Ogbia: ["Nembe", "Yenagoa"],
    Sagbama: ["Ekeremor", "Yenagoa"],
    "Southern Ijaw": ["Brass", "Ekeremor", "Kolokuma/Opokuma", "Yenagoa"],
    Yenagoa: ["Kolokuma/Opokuma", "Nembe", "Ogbia", "Sagbama", "Southern Ijaw"],
  },

  // BENUE STATE
  Benue: {
    Ado: ["Okpokwu", "Oju"],
    Agatu: ["Apa", "Oturkpo"],
    Apa: ["Agatu", "Oturkpo", "Gwer West"],
    Buruku: ["Gboko", "Tarka", "Ushongo", "Katsina-Ala", "Konshisha"],
    Gboko: ["Buruku", "Tarka", "Ushongo"],
    Guma: ["Makurdi", "Gwer West", "Gwer East", "Logo", "Tarka"],
    "Gwer East": ["Makurdi", "Gwer West", "Guma"],
    "Gwer West": ["Apa", "Gwer East", "Makurdi"],
    "Katsina-Ala": ["Buruku", "Ukum", "Logo"],
    Konshisha: ["Buruku", "Ushongo", "Vandeikya"],
    Kwande: ["Vandeikya", "Ushongo", "Logo"],
    Logo: ["Guma", "Katsina-Ala", "Ukum", "Kwande"],
    Makurdi: ["Guma", "Gwer East", "Gwer West"],
    Obi: ["Oju", "Oturkpo"],
    Ogbadibo: ["Okpokwu", "Oturkpo"],
    Ohimini: ["Oturkpo"],
    Oju: ["Ado", "Obi"],
    Okpokwu: ["Ado", "Ogbadibo", "Oturkpo"],
    Oturkpo: ["Agatu", "Apa", "Obi", "Ogbadibo", "Ohimini"],
    Tarka: ["Buruku", "Gboko", "Guma"],
    Ukum: ["Katsina-Ala", "Logo"],
    Ushongo: ["Buruku", "Gboko", "Konshisha", "Kwande"],
    Vandeikya: ["Konshisha", "Kwande"],
  },

  // BORNO STATE
  Borno: {
    Abadam: ["Mobbar", "Kukawa"],
    "Askira/Uba": ["Biu", "Chibok", "Hawul"],
    Bama: ["Konduga", "Gwoza", "Kala/Balge"],
    Bayo: ["Biu", "Hawul", "Shani"],
    Biu: ["Askira/Uba", "Bayo", "Hawul", "Kwaya Kusar"],
    Chibok: ["Askira/Uba", "Damboa"],
    Damboa: ["Chibok", "Gwoza", "Konduga"],
    Dikwa: ["Mafa", "Ngala", "Kala/Balge"],
    Gubio: ["Magumeri", "Mobbar", "Nganzai"],
    Guzamala: ["Kukawa", "Mobbar", "Nganzai"],
    Gwoza: ["Bama", "Damboa", "Konduga"],
    Hawul: ["Askira/Uba", "Bayo", "Biu", "Shani"],
    Jere: ["Maiduguri", "Konduga", "Mafa"],
    Kaga: ["Konduga", "Magumeri", "Mafa"],
    "Kala/Balge": ["Bama", "Dikwa", "Ngala"],
    Konduga: ["Bama", "Damboa", "Gwoza", "Jere", "Kaga", "Maiduguri"],
    Kukawa: ["Abadam", "Guzamala", "Mobbar", "Monguno"],
    "Kwaya Kusar": ["Biu", "Shani"],
    Mafa: ["Dikwa", "Jere", "Kaga"],
    Magumeri: ["Gubio", "Kaga", "Nganzai"],
    Maiduguri: ["Jere", "Konduga"],
    Marte: ["Monguno", "Ngala"],
    Mobbar: ["Abadam", "Gubio", "Guzamala", "Kukawa"],
    Monguno: ["Kukawa", "Marte", "Nganzai"],
    Ngala: ["Dikwa", "Kala/Balge", "Marte"],
    Nganzai: ["Gubio", "Guzamala", "Magumeri", "Monguno"],
    Shani: ["Bayo", "Hawul", "Kwaya Kusar"],
  },

  // CROSS RIVER STATE
  "Cross River": {
    Abi: ["Yakurr", "Obubra", "Biase"],
    Akamkpa: ["Akpabuyo", "Biase", "Odukpani"],
    Akpabuyo: ["Akamkpa", "Calabar South", "Bakassi"],
    Bakassi: ["Akpabuyo"],
    Bekwarra: ["Obudu", "Ogoja", "Yala"],
    Biase: ["Abi", "Akamkpa", "Odukpani"],
    Boki: ["Ikom", "Ogoja", "Obudu"],
    "Calabar Municipal": ["Calabar South", "Odukpani"],
    "Calabar South": ["Akpabuyo", "Calabar Municipal"],
    Etung: ["Ikom", "Obubra"],
    Ikom: ["Boki", "Etung", "Obubra"],
    Obanliku: ["Obudu"],
    Obubra: ["Abi", "Etung", "Ikom", "Yakurr"],
    Obudu: ["Bekwarra", "Boki", "Obanliku"],
    Odukpani: ["Akamkpa", "Biase", "Calabar Municipal"],
    Ogoja: ["Bekwarra", "Boki", "Yala"],
    Yakurr: ["Abi", "Obubra"],
    Yala: ["Bekwarra", "Ogoja"],
  },

  // DELTA STATE
  Delta: {
    "Aniocha North": ["Aniocha South", "Oshimili North"],
    "Aniocha South": ["Aniocha North", "Oshimili South", "Ika South"],
    Bomadi: ["Burutu", "Patani"],
    Burutu: ["Bomadi", "Warri South West"],
    "Ethiope East": ["Ethiope West", "Okpe", "Ughelli North"],
    "Ethiope West": ["Ethiope East", "Okpe", "Sapele", "Warri North"],
    "Ika North East": ["Ika South", "Oshimili South"],
    "Ika South": ["Aniocha South", "Ika North East", "Oshimili South"],
    "Isoko North": ["Isoko South", "Ndokwa East", "Ughelli South"],
    "Isoko South": ["Isoko North", "Ndokwa East", "Ughelli South", "Warri South"],
    "Ndokwa East": ["Isoko North", "Isoko South", "Ndokwa West", "Ukwuani"],
    "Ndokwa West": ["Ndokwa East", "Ukwuani"],
    Okpe: ["Ethiope East", "Ethiope West", "Sapele", "Ughelli North", "Uvwie"],
    "Oshimili North": ["Aniocha North", "Oshimili South"],
    "Oshimili South": ["Aniocha South", "Ika South", "Oshimili North"],
    Patani: ["Bomadi"],
    Sapele: ["Ethiope West", "Okpe", "Uvwie", "Warri North"],
    Udu: ["Ughelli South", "Uvwie", "Warri South"],
    "Ughelli North": ["Ethiope East", "Okpe", "Ughelli South"],
    "Ughelli South": ["Isoko North", "Isoko South", "Udu", "Ughelli North", "Warri South"],
    Ukwuani: ["Ndokwa East", "Ndokwa West"],
    Uvwie: ["Okpe", "Sapele", "Udu", "Warri South"],
    "Warri North": ["Ethiope West", "Sapele", "Warri South West"],
    "Warri South": ["Isoko South", "Udu", "Ughelli South", "Uvwie", "Warri South West"],
    "Warri South West": ["Burutu", "Warri North", "Warri South"],
  },

  // EBONYI STATE
  Ebonyi: {
    Abakaliki: ["Ebonyi", "Izzi", "Ohaukwu"],
    "Afikpo North": ["Afikpo South", "Ohaozara"],
    "Afikpo South": ["Afikpo North", "Ivo", "Ohaozara"],
    Ebonyi: ["Abakaliki", "Ikwo", "Izzi"],
    "Ezza North": ["Ezza South", "Ishielu", "Ohaukwu"],
    "Ezza South": ["Ezza North", "Ikwo", "Onicha"],
    Ikwo: ["Ebonyi", "Ezza South", "Onicha"],
    Ishielu: ["Ezza North", "Ohaukwu", "Onicha"],
    Ivo: ["Afikpo South", "Ohaozara"],
    Izzi: ["Abakaliki", "Ebonyi", "Ohaukwu"],
    Ohaozara: ["Afikpo North", "Afikpo South", "Ivo", "Onicha"],
    Ohaukwu: ["Abakaliki", "Ezza North", "Ishielu", "Izzi"],
    Onicha: ["Ezza South", "Ikwo", "Ishielu", "Ohaozara"],
  },

  // EDO STATE
  Edo: {
    "Akoko-Edo": ["Etsako West", "Owan East"],
    Egor: ["Ikpoba-Okha", "Oredo", "Ovia North-East"],
    "Esan Central": ["Esan North-East", "Esan South-East", "Esan West"],
    "Esan North-East": ["Esan Central", "Esan South-East", "Etsako Central"],
    "Esan South-East": ["Esan Central", "Esan North-East", "Esan West", "Igueben", "Uhunmwonde"],
    "Esan West": ["Esan Central", "Esan South-East", "Igueben", "Orhionmwon"],
    "Etsako Central": ["Esan North-East", "Etsako East", "Etsako West"],
    "Etsako East": ["Etsako Central", "Etsako West"],
    "Etsako West": ["Akoko-Edo", "Etsako Central", "Etsako East", "Owan East"],
    Igueben: ["Esan South-East", "Esan West", "Orhionmwon"],
    "Ikpoba Okha": ["Egor", "Oredo", "Uhunmwonde"],
    Orhionmwon: ["Esan West", "Igueben", "Uhunmwonde"],
    Oredo: ["Egor", "Ikpoba-Okha", "Ovia North-East"],
    "Ovia North-East": ["Egor", "Oredo", "Ovia South-West"],
    "Ovia South-West": ["Ovia North-East", "Owan West"],
    "Owan East": ["Akoko-Edo", "Etsako West", "Owan West"],
    "Owan West": ["Ovia South-West", "Owan East"],
    Uhunmwonde: ["Esan South-East", "Ikpoba-Okha", "Orhionmwon"],
  },

  // EKITI STATE
  Ekiti: {
    "Ado Ekiti": ["Ikere", "Irepodun/Ifelodun", "Ise/Orun"],
    Efon: ["Ekiti West", "Ijero"],
    "Ekiti East": ["Gbonyin", "Ikole", "Ise/Orun"],
    "Ekiti South-West": ["Ikere", "Ise/Orun"],
    "Ekiti West": ["Efon", "Ijero", "Irepodun/Ifelodun"],
    Emure: ["Ise/Orun"],
    Gbonyin: ["Ekiti East", "Ido Osi", "Ikole"],
    "Ido Osi": ["Gbonyin", "Ilejemeje", "Moba"],
    Ijero: ["Efon", "Ekiti West", "Moba"],
    Ikere: ["Ado Ekiti", "Ekiti South-West", "Ise/Orun"],
    Ikole: ["Ekiti East", "Gbonyin", "Ilejemeje", "Oye"],
    Ilejemeje: ["Ido Osi", "Ikole", "Moba", "Oye"],
    "Irepodun/Ifelodun": ["Ado Ekiti", "Ekiti West"],
    "Ise/Orun": ["Ado Ekiti", "Ekiti East", "Ekiti South-West", "Emure", "Ikere"],
    Moba: ["Ido Osi", "Ijero", "Ilejemeje"],
    Oye: ["Ikole", "Ilejemeje"],
  },

  // ENUGU STATE
  Enugu: {
    Aninri: ["Awgu", "Oji River"],
    Awgu: ["Aninri", "Nkanu West", "Oji River"],
    "Enugu East": ["Enugu North", "Enugu South", "Isi Uzo", "Nkanu West"],
    "Enugu North": ["Enugu East", "Enugu South", "Udi"],
    "Enugu South": ["Enugu East", "Enugu North", "Nkanu West"],
    Ezeagu: ["Udi", "Oji River", "Uzo Uwani"],
    "Igbo Etiti": ["Igbo Eze South", "Isi Uzo", "Uzo Uwani", "Udi"],
    "Igbo Eze North": ["Igbo Eze South", "Udenu"],
    "Igbo Eze South": ["Igbo Eze North", "Igbo Etiti", "Isi Uzo", "Udenu"],
    "Isi Uzo": ["Enugu East", "Igbo Eze South", "Nsukka", "Udenu"],
    "Nkanu East": ["Nkanu West"],
    "Nkanu West": ["Awgu", "Enugu East", "Enugu South", "Nkanu East"],
    Nsukka: ["Isi Uzo", "Udenu", "Uzo Uwani"],
    "Oji River": ["Aninri", "Awgu", "Ezeagu"],
    Udenu: ["Igbo Eze North", "Igbo Eze South", "Isi Uzo", "Nsukka"],
    Udi: ["Enugu North", "Ezeagu", "Igbo Etiti"],
    "Uzo Uwani": ["Ezeagu", "Igbo Etiti", "Nsukka"],
  },

  // FCT (ABUJA)
  FCT: {
    Abaji: ["Gwagwalada", "Kwali"],
    Bwari: ["Gwagwalada", "Municipal Area Council"],
    Gwagwalada: ["Abaji", "Bwari", "Kuje", "Kwali", "Municipal Area Council"],
    Kuje: ["Gwagwalada", "Municipal Area Council"],
    Kwali: ["Abaji", "Gwagwalada"],
    "Municipal Area Council": ["Bwari", "Gwagwalada", "Kuje"],
  },

  // GOMBE STATE
  Gombe: {
    Akko: ["Billiri", "Dukku", "Gombe", "Kwami", "Yamaltu/Deba"],
    Balanga: ["Billiri", "Kaltungo", "Shongom", "Yamaltu/Deba"],
    Billiri: ["Akko", "Balanga", "Kaltungo", "Yamaltu/Deba"],
    Dukku: ["Akko", "Funakaye", "Gombe", "Kwami", "Nafada"],
    Funakaye: ["Dukku", "Nafada"],
    Gombe: ["Akko", "Dukku", "Kwami"],
    Kaltungo: ["Balanga", "Billiri", "Shongom"],
    Kwami: ["Akko", "Dukku", "Gombe"],
    Nafada: ["Dukku", "Funakaye"],
    Shongom: ["Balanga", "Kaltungo"],
    "Yamaltu/Deba": ["Akko", "Balanga", "Billiri"],
  },

  // IMO STATE
  Imo: {
    "Aboh Mbaise": ["Ahiazu Mbaise", "Ezinihitte", "Ngor Okpala"],
    "Ahiazu Mbaise": ["Aboh Mbaise", "Ezinihitte"],
    "Ehime Mbano": ["Ihitte/Uboma", "Isiala Mbano", "Obowo"],
    Ezinihitte: ["Aboh Mbaise", "Ahiazu Mbaise"],
    "Ideato North": ["Ideato South", "Isu", "Njaba", "Orlu"],
    "Ideato South": ["Ideato North", "Isu", "Orsu"],
    "Ihitte/Uboma": ["Ehime Mbano", "Isiala Mbano", "Obowo"],
    Ikeduru: ["Mbaitoli", "Owerri West"],
    "Isiala Mbano": ["Ehime Mbano", "Ihitte/Uboma", "Onuimo"],
    Isu: ["Ideato North", "Ideato South", "Nwangele", "Orsu"],
    Mbaitoli: ["Ikeduru", "Ngor Okpala", "Owerri North", "Owerri West"],
    "Ngor Okpala": ["Aboh Mbaise", "Mbaitoli", "Owerri North"],
    Njaba: ["Ideato North", "Isu", "Nwangele", "Orlu"],
    Nkwerre: ["Isu", "Nwangele", "Orlu"],
    Nwangele: ["Isu", "Njaba", "Nkwerre"],
    Obowo: ["Ehime Mbano", "Ihitte/Uboma"],
    Oguta: ["Ohaji/Egbema", "Oru West"],
    "Ohaji/Egbema": ["Oguta", "Oru West"],
    Okigwe: ["Onuimo"],
    Orlu: ["Ideato North", "Njaba", "Nkwerre", "Oru East"],
    Orsu: ["Ideato South", "Isu", "Oru East"],
    "Oru East": ["Orlu", "Orsu", "Oru West"],
    "Oru West": ["Oguta", "Ohaji/Egbema", "Oru East"],
    "Owerri Municipal": ["Owerri North", "Owerri West"],
    "Owerri North": ["Mbaitoli", "Ngor Okpala", "Owerri Municipal", "Owerri West"],
    "Owerri West": ["Ikeduru", "Mbaitoli", "Owerri Municipal", "Owerri North"],
    Unuimo: ["Isiala Mbano", "Okigwe"],
  },

  // JIGAWA STATE
  Jigawa: {
    Auyo: ["Hadejia", "Kafin Hausa", "Kaugama"],
    Babura: ["Garki", "Gumel", "Maigatari", "Sule Tankarkar"],
    Biriniwa: ["Guri", "Jahun", "Kaugama", "Kiri Kasamma"],
    "Birnin Kudu": ["Buji", "Dutse", "Gwaram", "Kiyawa"],
    Buji: ["Birnin Kudu", "Dutse", "Kiyawa"],
    Dutse: ["Birnin Kudu", "Buji", "Kiyawa", "Ringim"],
    Gagarawa: ["Gumel", "Maigatari", "Taura"],
    Garki: ["Babura", "Gumel", "Ringim", "Taura"],
    Gumel: ["Babura", "Gagarawa", "Garki", "Maigatari", "Sule Tankarkar"],
    Guri: ["Biriniwa", "Kiri Kasamma"],
    Gwaram: ["Birnin Kudu", "Kiyawa"],
    Gwiwa: ["Kazaure", "Yankwashi"],
    Hadejia: ["Auyo", "Kafin Hausa", "Kaugama", "Kiri Kasamma", "Malam Madori"],
    Jahun: ["Biriniwa", "Kafin Hausa", "Miga", "Ringim"],
    "Kafin Hausa": ["Auyo", "Hadejia", "Jahun", "Kaugama", "Malam Madori"],
    Kazaure: ["Gwiwa", "Roni", "Yankwashi"],
    "Kiri Kasamma": ["Biriniwa", "Guri", "Hadejia"],
    Kiyawa: ["Birnin Kudu", "Buji", "Dutse", "Gwaram"],
    Kaugama: ["Auyo", "Biriniwa", "Hadejia", "Kafin Hausa", "Malam Madori"],
    Maigatari: ["Babura", "Gagarawa", "Gumel", "Sule Tankarkar"],
    "Malam Madori": ["Hadejia", "Kafin Hausa", "Kaugama"],
    Miga: ["Jahun", "Ringim"],
    Ringim: ["Dutse", "Garki", "Jahun", "Miga", "Taura"],
    Roni: ["Kazaure", "Yankwashi"],
    "Sule Tankarkar": ["Babura", "Gumel", "Maigatari"],
    Taura: ["Gagarawa", "Garki", "Ringim"],
    Yankwashi: ["Gwiwa", "Kazaure", "Roni"],
  },

  // KADUNA STATE
  Kaduna: {
    "Birnin Gwari": ["Chikun", "Giwa", "Igabi"],
    Chikun: ["Birnin Gwari", "Igabi", "Kajuru", "Kachia"],
    Giwa: ["Birnin Gwari", "Igabi", "Sabon Gari"],
    Igabi: ["Birnin Gwari", "Chikun", "Giwa", "Kaduna North", "Zaria"],
    Ikara: ["Kubau", "Makarfi", "Soba"],
    Jaba: ["Jema'a", "Kachia", "Kagarko"],
    "Jema'a": ["Jaba", "Kachia", "Kagarko", "Kaura", "Zangon Kataf"],
    Kachia: ["Chikun", "Jaba", "Jema'a", "Kajuru", "Kagarko", "Zangon Kataf"],
    "Kaduna North": ["Igabi", "Kaduna South"],
    "Kaduna South": ["Kaduna North", "Chikun"],
    Kagarko: ["Jaba", "Jema'a", "Kachia"],
    Kajuru: ["Chikun", "Kachia", "Zangon Kataf"],
    Kaura: ["Jema'a", "Zangon Kataf"],
    Kauru: ["Lere", "Sanga", "Zangon Kataf"],
    Kubau: ["Ikara", "Kudan", "Lere", "Soba"],
    Kudan: ["Kubau", "Makarfi", "Sabon Gari", "Soba", "Zaria"],
    Lere: ["Kauru", "Kubau", "Sanga"],
    Makarfi: ["Ikara", "Kudan", "Sabon Gari", "Soba"],
    "Sabon Gari": ["Giwa", "Kudan", "Makarfi", "Zaria"],
    Sanga: ["Kauru", "Lere"],
    Soba: ["Ikara", "Kubau", "Kudan", "Makarfi", "Zaria"],
    "Zangon Kataf": ["Jema'a", "Kachia", "Kajuru", "Kaura", "Kauru"],
    Zaria: ["Igabi", "Kudan", "Sabon Gari", "Soba"],
  },

  // KANO STATE
  Kano: {
    Ajingi: ["Albasu", "Gaya", "Wudil"],
    Albasu: ["Ajingi", "Gaya", "Takai"],
    Bagwai: ["Bebeji", "Bichi", "Shanono"],
    Bebeji: ["Bagwai", "Bichi", "Kiru", "Rano"],
    Bichi: ["Bagwai", "Bebeji", "Dambatta", "Makoda", "Shanono", "Tsanyawa"],
    Bunkure: ["Kibiya", "Kura", "Rano"],
    Dala: ["Fagge", "Gwale", "Kano Municipal", "Kumbotso"],
    Dambatta: ["Bichi", "Makoda", "Minjibir", "Tsanyawa"],
    "Dawakin Kudu": ["Kumbotso", "Madobi", "Minjibir", "Warawa"],
    "Dawakin Tofa": ["Bichi", "Rimingado", "Tofa"],
    Doguwa: ["Kibiya", "Sumaila", "Tudun Wada"],
    Fagge: ["Dala", "Gwale", "Kano Municipal", "Nasarawa"],
    Gabasawa: ["Gezawa", "Minjibir", "Tofa"],
    Garko: ["Albasu", "Kibiya", "Sumaila", "Wudil"],
    "Garun Malam": ["Kura", "Madobi"],
    Gaya: ["Ajingi", "Albasu", "Wudil"],
    Gezawa: ["Gabasawa", "Minjibir", "Warawa"],
    Gwale: ["Dala", "Fagge", "Kano Municipal", "Kumbotso", "Nasarawa"],
    Gwarzo: ["Karaye", "Kabo", "Rimin Gado", "Shanono"],
    Kabo: ["Bichi", "Gwarzo", "Madobi", "Tofa"],
    "Kano Municipal": ["Dala", "Fagge", "Gwale", "Nasarawa", "Tarauni"],
    Karaye: ["Gwarzo", "Kabo", "Rimin Gado"],
    Kibiya: ["Bunkure", "Doguwa", "Garko", "Rano", "Tudun Wada"],
    Kiru: ["Bebeji", "Madobi", "Rano"],
    Kumbotso: ["Dala", "Dawakin Kudu", "Gwale", "Madobi", "Nasarawa", "Ungogo"],
    Kunchi: ["Bichi", "Dambatta", "Tsanyawa"],
    Kura: ["Bunkure", "Garun Malam", "Madobi"],
    Madobi: ["Dawakin Kudu", "Garun Malam", "Kabo", "Kiru", "Kumbotso", "Kura"],
    Makoda: ["Bichi", "Dambatta", "Minjibir"],
    Minjibir: ["Dambatta", "Dawakin Kudu", "Gabasawa", "Gezawa", "Makoda"],
    Nasarawa: ["Fagge", "Gwale", "Kano Municipal", "Kumbotso", "Tarauni", "Ungogo"],
    Rano: ["Bebeji", "Bunkure", "Kibiya", "Kiru", "Tudun Wada"],
    "Rimin Gado": ["Gwarzo", "Karaye", "Tofa", "Ungogo"],
    Rogo: ["Karaye", "Kiru"],
    Shanono: ["Bagwai", "Bichi", "Gwarzo", "Tsanyawa"],
    Sumaila: ["Doguwa", "Garko", "Takai"],
    Takai: ["Albasu", "Sumaila"],
    Tarauni: ["Kano Municipal", "Nasarawa", "Ungogo"],
    Tofa: ["Dawakin Tofa", "Gabasawa", "Kabo", "Rimin Gado", "Tsanyawa"],
    Tsanyawa: ["Bichi", "Dambatta", "Kunchi", "Shanono", "Tofa"],
    "Tudun Wada": ["Doguwa", "Kibiya", "Rano"],
    Ungogo: ["Kumbotso", "Nasarawa", "Rimin Gado", "Tarauni", "Warawa"],
    Warawa: ["Dawakin Kudu", "Gezawa", "Ungogo", "Wudil"],
    Wudil: ["Ajingi", "Garko", "Gaya", "Warawa"],
  },

  // KATSINA STATE
  Katsina: {
    Bakori: ["Danja", "Funtua", "Malumfashi"],
    Batagarawa: ["Batsari", "Charanchi", "Katsina", "Rimi"],
    Batsari: ["Batagarawa", "Charanchi", "Jibia", "Kurfi", "Safana"],
    Baure: ["Bindawa", "Daura", "Mashi", "Zango"],
    Bindawa: ["Baure", "Daura", "Dutsi", "Kankia", "Mani"],
    Charanchi: ["Batagarawa", "Batsari", "Kankia", "Kurfi", "Rimi"],
    Dandume: ["Faskari", "Funtua", "Sabuwa"],
    Danja: ["Bakori", "Funtua"],
    "Dan Musa": ["Batsari", "Faskari", "Jibia", "Kankara", "Safana"],
    Daura: ["Baure", "Bindawa", "Mai'Adua", "Mashi", "Zango"],
    Dutsi: ["Bindawa", "Kankia", "Mani"],
    "Dutsin Ma": ["Kurfi", "Kankara", "Safana"],
    Faskari: ["Dandume", "Dan Musa", "Kankara", "Sabuwa"],
    Funtua: ["Bakori", "Dandume", "Danja", "Malumfashi"],
    Ingawa: ["Kankia", "Kusada", "Mani"],
    Jibia: ["Batsari", "Dan Musa", "Kaita", "Katsina"],
    Kafur: ["Danja", "Malumfashi"],
    Kaita: ["Jibia", "Katsina", "Rimi"],
    Kankara: ["Dan Musa", "Dutsin Ma", "Faskari", "Sabuwa"],
    Kankia: ["Bindawa", "Charanchi", "Dutsi", "Ingawa", "Kusada"],
    Katsina: ["Batagarawa", "Jibia", "Kaita", "Rimi"],
    Kurfi: ["Batsari", "Charanchi", "Dutsin Ma", "Rimi", "Safana"],
    Kusada: ["Ingawa", "Kankia"],
    "Mai'Adua": ["Daura", "Mashi", "Zango"],
    Malumfashi: ["Bakori", "Funtua", "Kafur"],
    Mani: ["Bindawa", "Dutsi", "Ingawa"],
    Mashi: ["Baure", "Daura", "Mai'Adua"],
    Matazu: ["Musawa", "Rimi"],
    Musawa: ["Matazu", "Rimi"],
    Rimi: ["Batagarawa", "Charanchi", "Kaita", "Katsina", "Kurfi", "Matazu", "Musawa"],
    Sabuwa: ["Dandume", "Faskari", "Kankara"],
    Safana: ["Batsari", "Dan Musa", "Dutsin Ma", "Kurfi"],
    Sandamu: ["Daura", "Zango"],
    Zango: ["Baure", "Daura", "Mai'Adua", "Sandamu"],
  },

  // KEBBI STATE
  Kebbi: {
    Aleiro: ["Birnin Kebbi", "Gwandu", "Jega"],
    "Arewa Dandi": ["Argungu", "Augie", "Bagudo"],
    Argungu: ["Arewa Dandi", "Augie", "Birnin Kebbi", "Dandi"],
    Augie: ["Arewa Dandi", "Argungu", "Dandi"],
    Bagudo: ["Arewa Dandi", "Bunza", "Dandi", "Koko/Besse", "Suru"],
    "Birnin Kebbi": ["Aleiro", "Argungu", "Bunza", "Gwandu", "Kalgo"],
    Bunza: ["Bagudo", "Birnin Kebbi", "Kalgo", "Koko/Besse", "Suru"],
    Dandi: ["Argungu", "Augie", "Bagudo"],
    Fakai: ["Ngaski", "Sakaba", "Wasagu/Danko", "Zuru"],
    Gwandu: ["Aleiro", "Birnin Kebbi", "Jega", "Kalgo"],
    Jega: ["Aleiro", "Gwandu", "Kalgo", "Maiyama"],
    Kalgo: ["Birnin Kebbi", "Bunza", "Gwandu", "Jega"],
    "Koko/Besse": ["Bagudo", "Bunza", "Maiyama", "Suru"],
    Maiyama: ["Jega", "Koko/Besse", "Suru"],
    Ngaski: ["Fakai", "Shanga", "Yauri"],
    Sakaba: ["Fakai", "Wasagu/Danko", "Zuru"],
    Shanga: ["Ngaski", "Yauri"],
    Suru: ["Bagudo", "Bunza", "Koko/Besse", "Maiyama"],
    "Wasagu/Danko": ["Fakai", "Sakaba", "Zuru"],
    Yauri: ["Ngaski", "Shanga"],
    Zuru: ["Fakai", "Sakaba", "Wasagu/Danko"],
  },

  // KOGI STATE
  Kogi: {
    Adavi: ["Ajaokuta", "Okene", "Okehi"],
    Ajaokuta: ["Adavi", "Bassa", "Lokoja", "Okene"],
    Ankpa: ["Dekina", "Olamaboro", "Omala"],
    Bassa: ["Ajaokuta", "Dekina", "Lokoja"],
    Dekina: ["Ankpa", "Bassa", "Omala", "Ofu", "Idah", "Igalamela Odolu"],
    Ibaji: ["Idah", "Igalamela Odolu"],
    Idah: ["Dekina", "Ibaji", "Igalamela Odolu"],
    "Igalamela Odolu": ["Dekina", "Idah", "Ibaji", "Ofu"],
    Ijumu: ["Kabba/Bunu", "Kogi", "Lokoja", "Mopa Muro"],
    "Kabba/Bunu": ["Ijumu", "Kogi", "Mopa Muro", "Yagba East"],
    Kogi: ["Ijumu", "Kabba/Bunu", "Lokoja"],
    Lokoja: ["Ajaokuta", "Bassa", "Ijumu", "Kogi"],
    "Mopa Muro": ["Ijumu", "Kabba/Bunu", "Yagba East"],
    Ofu: ["Dekina", "Igalamela Odolu"],
    "Ogori/Magongo": ["Okene", "Okehi"],
    Okehi: ["Adavi", "Ogori/Magongo", "Okene"],
    Okene: ["Adavi", "Ajaokuta", "Ogori/Magongo", "Okehi"],
    Olamaboro: ["Ankpa", "Omala"],
    Omala: ["Ankpa", "Dekina", "Olamaboro"],
    "Yagba East": ["Kabba/Bunu", "Mopa Muro", "Yagba West"],
    "Yagba West": ["Yagba East"],
  },

  // KWARA STATE
  Kwara: {
    Asa: ["Ilorin East", "Ilorin West", "Moro"],
    Baruten: ["Kaiama"],
    Edu: ["Moro", "Pategi"],
    Ekiti: ["Irepodun", "Isin", "Oke Ero"],
    Ifelodun: ["Irepodun", "Offa", "Oyun"],
    "Ilorin East": ["Asa", "Ilorin South", "Ilorin West", "Moro"],
    "Ilorin South": ["Ilorin East", "Ilorin West"],
    "Ilorin West": ["Asa", "Ilorin East", "Ilorin South"],
    Irepodun: ["Ekiti", "Ifelodun", "Isin", "Offa", "Oke Ero", "Oyun"],
    Isin: ["Ekiti", "Irepodun", "Oke Ero"],
    Kaiama: ["Baruten", "Moro"],
    Moro: ["Asa", "Edu", "Ilorin East", "Kaiama"],
    Offa: ["Ifelodun", "Irepodun", "Oyun"],
    "Oke Ero": ["Ekiti", "Irepodun", "Isin"],
    Oyun: ["Ifelodun", "Irepodun", "Offa"],
    Pategi: ["Edu"],
  },

  // NASARAWA STATE
  Nasarawa: {
    Akwanga: ["Kokona", "Nasarawa Egon", "Wamba"],
    Awe: ["Doma", "Keana", "Obi"],
    Doma: ["Awe", "Keana", "Lafia", "Nasarawa"],
    Karu: ["Keffi", "Kokona", "Nasarawa"],
    Keana: ["Awe", "Doma", "Obi"],
    Keffi: ["Karu", "Kokona", "Nasarawa"],
    Kokona: ["Akwanga", "Karu", "Keffi", "Lafia", "Nasarawa", "Nasarawa Egon"],
    Lafia: ["Doma", "Kokona", "Nasarawa Egon", "Obi"],
    Nasarawa: ["Doma", "Karu", "Keffi", "Kokona", "Toto"],
    "Nasarawa Egon": ["Akwanga", "Kokona", "Lafia", "Wamba"],
    Obi: ["Awe", "Keana", "Lafia"],
    Toto: ["Nasarawa"],
    Wamba: ["Akwanga", "Nasarawa Egon"],
  },

  // NIGER STATE
  Niger: {
    Agaie: ["Bida", "Edati", "Lapai"],
    Agwara: ["Borgu"],
    Bida: ["Agaie", "Edati", "Gbako", "Katcha", "Lavun", "Mokwa"],
    Borgu: ["Agwara", "Magama", "Mokwa"],
    Bosso: ["Chanchaga", "Minna", "Paikoro", "Shiroro"],
    Chanchaga: ["Bosso", "Minna", "Shiroro"],
    Edati: ["Agaie", "Bida", "Gbako", "Lavun", "Mokwa"],
    Gbako: ["Bida", "Edati", "Katcha", "Lavun"],
    Gurara: ["Minna", "Suleja", "Tafa"],
    Katcha: ["Bida", "Gbako", "Lavun"],
    Kontagora: ["Magama", "Mariga", "Mashegu", "Wushishi"],
    Lapai: ["Agaie", "Edati", "Minna", "Paikoro", "Suleja"],
    Lavun: ["Bida", "Edati", "Gbako", "Katcha", "Mokwa"],
    Magama: ["Borgu", "Kontagora", "Mariga", "Rijau"],
    Mariga: ["Kontagora", "Magama", "Mashegu", "Rafi", "Wushishi"],
    Mashegu: ["Kontagora", "Mariga", "Wushishi"],
    Mokwa: ["Bida", "Borgu", "Edati", "Lavun"],
    Moya: ["Rafi", "Shiroro"],
    Paikoro: ["Bosso", "Gurara", "Lapai", "Minna", "Rafi", "Shiroro"],
    Rafi: ["Mariga", "Moya", "Paikoro", "Shiroro", "Wushishi"],
    Rijau: ["Magama", "Mariga"],
    Shiroro: ["Bosso", "Chanchaga", "Minna", "Moya", "Paikoro", "Rafi"],
    Suleja: ["Gurara", "Lapai", "Tafa"],
    Tafa: ["Gurara", "Suleja"],
    Wushishi: ["Kontagora", "Mariga", "Mashegu", "Rafi"],
  },

  // OGUN STATE
  Ogun: {
    "Abeokuta North": ["Abeokuta South", "Ewekoro", "Ifo", "Odeda"],
    "Abeokuta South": ["Abeokuta North", "Obafemi Owode"],
    "Ado-Odo/Ota": ["Ifo", "Ipokia", "Yewa South"],
    "Egbado North": ["Egbado South", "Imeko Afon", "Ipokia", "Yewa South"],
    "Egbado South": ["Egbado North", "Ipokia", "Yewa South"],
    Ewekoro: ["Abeokuta North", "Ifo", "Yewa South"],
    Ifo: ["Abeokuta North", "Ado-Odo/Ota", "Ewekoro", "Obafemi Owode"],
    "Ijebu East": ["Ijebu North", "Ijebu North East", "Ogun Waterside"],
    "Ijebu North": ["Ijebu East", "Ijebu North East", "Ijebu Ode", "Ikenne", "Odogbolu"],
    "Ijebu North East": ["Ijebu East", "Ijebu North", "Ijebu Ode", "Odogbolu"],
    "Ijebu Ode": ["Ijebu North", "Ijebu North East", "Odogbolu"],
    Ikenne: ["Ijebu North", "Obafemi Owode", "Remo North", "Sagamu"],
    "Imeko Afon": ["Egbado North", "Yewa North"],
    Ipokia: ["Ado-Odo/Ota", "Egbado North", "Egbado South", "Yewa South"],
    "Obafemi Owode": ["Abeokuta South", "Ifo", "Ikenne", "Sagamu"],
    Odeda: ["Abeokuta North"],
    Odogbolu: ["Ijebu North", "Ijebu North East", "Ijebu Ode"],
    "Ogun Waterside": ["Ijebu East"],
    "Remo North": ["Ikenne", "Sagamu"],
    Sagamu: ["Ikenne", "Obafemi Owode", "Remo North"],
    "Yewa North": ["Imeko Afon"],
    "Yewa South": ["Ado-Odo/Ota", "Egbado South", "Ewekoro", "Ipokia"],
  },

  // ONDO STATE
  Ondo: {
    "Akoko North-East": ["Akoko North-West", "Akoko South-East"],
    "Akoko North-West": ["Akoko North-East", "Akoko South-West"],
    "Akoko South-East": ["Akoko North-East", "Akoko South-West"],
    "Akoko South-West": ["Akoko North-West", "Akoko South-East", "Owo"],
    "Akure North": ["Akure South", "Ifedore", "Owo"],
    "Akure South": ["Akure North", "Idanre", "Ifedore"],
    "Ese Odo": ["Ilaje", "Irele"],
    Idanre: ["Akure South", "Ifedore", "Ile Oluji/Okeigbo"],
    Ifedore: ["Akure North", "Akure South", "Idanre", "Ile Oluji/Okeigbo", "Ondo East"],
    Ilaje: ["Ese Odo", "Irele", "Okitipupa", "Odigbo"],
    "Ile Oluji/Okeigbo": ["Idanre", "Ifedore", "Ondo East", "Ondo West", "Odigbo"],
    Irele: ["Ese Odo", "Ilaje", "Okitipupa"],
    Odigbo: ["Ilaje", "Ile Oluji/Okeigbo", "Ondo West"],
    Okitipupa: ["Ilaje", "Irele"],
    "Ondo East": ["Ifedore", "Ile Oluji/Okeigbo", "Ondo West"],
    "Ondo West": ["Ile Oluji/Okeigbo", "Ondo East", "Odigbo"],
    Ose: ["Akoko South-West", "Owo"],
    Owo: ["Akoko South-West", "Akure North", "Ose"],
  },

  // OSUN STATE
  Osun: {
    "Atakunmosa East": ["Atakunmosa West", "Ilesa East", "Obokun"],
    "Atakunmosa West": ["Atakunmosa East", "Ilesa West", "Obokun", "Oriade"],
    Aiyedaade: ["Ayedire", "Ede North", "Egbedore", "Irewole"],
    Aiyedire: ["Aiyedaade", "Ede North", "Iwo"],
    Boluwaduro: ["Ila", "Ifedayo", "Oriade"],
    Boripe: ["Ifelodun", "Ila", "Odo Otin", "Olorunda"],
    "Ede North": ["Aiyedaade", "Aiyedire", "Ede South", "Egbedore"],
    "Ede South": ["Ede North", "Egbedore", "Osogbo"],
    "Ife Central": ["Ife East", "Ife North", "Ife South"],
    "Ife East": ["Ife Central", "Ife North", "Ife South", "Ilesha East"],
    "Ife North": ["Ife Central", "Ife East", "Ife South", "Oriade"],
    "Ife South": ["Ife Central", "Ife East", "Ife North"],
    Egbedore: ["Aiyedaade", "Ede North", "Ede South", "Irepodun", "Osogbo"],
    Ejigbo: ["Iwo", "Ola Oluwa"],
    Ifedayo: ["Boluwaduro", "Ila", "Oriade"],
    Ifelodun: ["Boripe", "Odo Otin", "Olorunda", "Osogbo"],
    Ila: ["Boluwaduro", "Boripe", "Ifedayo"],
    "Ilesa East": ["Atakunmosa East", "Ilesa West", "Obokun"],
    "Ilesa West": ["Atakunmosa West", "Ilesa East", "Oriade"],
    Irepodun: ["Egbedore", "Olorunda", "Osogbo"],
    Irewole: ["Aiyedaade", "Isokan"],
    Isokan: ["Irewole"],
    Iwo: ["Aiyedire", "Ejigbo", "Ola Oluwa"],
    Obokun: ["Atakunmosa East", "Atakunmosa West", "Ilesa East"],
    "Odo Otin": ["Boripe", "Ifelodun"],
    "Ola Oluwa": ["Ejigbo", "Iwo"],
    Olorunda: ["Boripe", "Ifelodun", "Irepodun", "Osogbo"],
    Oriade: ["Atakunmosa West", "Boluwaduro", "Ifedayo", "Ife North", "Ilesa West"],
    Orolu: ["Irepodun", "Osogbo"],
    Osogbo: ["Ede South", "Egbedore", "Ifelodun", "Irepodun", "Olorunda", "Orolu"],
  },

  // OYO STATE
  Oyo: {
    Afijio: ["Akinyele", "Oyo East", "Oyo"],
    Akinyele: ["Afijio", "Egbeda", "Ido", "Lagelu", "Oyo East"],
    Atiba: ["Oyo East", "Oyo"],
    Atisbo: ["Itesiwaju", "Iwajowa", "Saki East"],
    Egbeda: ["Akinyele", "Ibadan North", "Ibadan North East", "Ibadan South West", "Lagelu", "Ona Ara"],
    "Ibadan North": ["Egbeda", "Ibadan North East", "Ibadan North West", "Ibadan South East", "Ibadan South West"],
    "Ibadan North-East": ["Egbeda", "Ibadan North", "Ibadan South East"],
    "Ibadan North-West": ["Ibadan North", "Ibadan South West"],
    "Ibadan South-East": ["Ibadan North", "Ibadan North East", "Ibadan South West"],
    "Ibadan South-West": ["Egbeda", "Ibadan North", "Ibadan North West", "Ibadan South East", "Ona Ara"],
    "Ibarapa Central": ["Ibarapa East", "Ibarapa North"],
    "Ibarapa East": ["Ibarapa Central", "Ibarapa North"],
    "Ibarapa North": ["Ibarapa Central", "Ibarapa East", "Ido"],
    Ido: ["Akinyele", "Ibarapa North", "Oluyole"],
    Irepo: ["Olorunsogo", "Orelope", "Saki East"],
    Iseyin: ["Itesiwaju", "Iwajowa", "Kajola", "Oyo"],
    Itesiwaju: ["Atisbo", "Iseyin", "Iwajowa", "Kajola"],
    Iwajowa: ["Atisbo", "Iseyin", "Itesiwaju", "Kajola"],
    Kajola: ["Iseyin", "Itesiwaju", "Iwajowa", "Oyo"],
    Lagelu: ["Akinyele", "Egbeda", "Ona Ara"],
    "Ogbomosho North": ["Ogbomosho South", "Ori Ire", "Oyo", "Surulere"],
    "Ogbomosho South": ["Ogbomosho North", "Ogo Oluwa", "Surulere"],
    "Ogo Oluwa": ["Ogbomosho South", "Surulere"],
    Olorunsogo: ["Irepo", "Orelope"],
    Oluyole: ["Ido", "Ona Ara"],
    "Ona Ara": ["Egbeda", "Ibadan South West", "Lagelu", "Oluyole"],
    Orelope: ["Irepo", "Olorunsogo", "Saki East"],
    "Ori Ire": ["Ogbomosho North", "Oyo"],
    "Oyo": ["Oyo East", "Ori Ire", "Ogbomosho North", "Atiba", "Iseyin", "Afijio"],
    "Oyo East": ["Afijio", "Akinyele", "Atiba", "Oyo"],
    "Saki East": ["Atisbo", "Irepo", "Orelope", "Saki West"],
    "Saki West": ["Saki East"],
    Surulere: ["Ogbomosho North", "Ogbomosho South", "Ogo Oluwa"],
  },

  // PLATEAU STATE
  Plateau: {
    "Barkin Ladi": ["Bokkos", "Jos South", "Mangu", "Riyom"],
    Bassa: ["Jos East", "Jos North"],
    Bokkos: ["Barkin Ladi", "Mangu", "Pankshin", "Wase"],
    "Jos East": ["Bassa", "Jos North", "Jos South"],
    "Jos North": ["Bassa", "Jos East", "Jos South"],
    "Jos South": ["Barkin Ladi", "Jos East", "Jos North", "Riyom"],
    Kanam: ["Kanke", "Langtang North", "Mikang", "Pankshin", "Qua'an Pan", "Wase"],
    Kanke: ["Kanam", "Langtang North", "Mikang", "Pankshin"],
    "Langtang North": ["Kanam", "Kanke", "Langtang South", "Mikang", "Qua'an Pan", "Shendam", "Wase"],
    "Langtang South": ["Langtang North", "Mikang", "Qua'an Pan", "Shendam"],
    Mangu: ["Barkin Ladi", "Bokkos", "Pankshin"],
    Mikang: ["Kanam", "Kanke", "Langtang North", "Langtang South", "Qua'an Pan", "Shendam"],
    Pankshin: ["Bokkos", "Kanam", "Kanke", "Mangu"],
    "Qua'an Pan": ["Kanam", "Langtang North", "Langtang South", "Mikang", "Shendam"],
    Riyom: ["Barkin Ladi", "Jos South"],
    Shendam: ["Langtang North", "Langtang South", "Mikang", "Qua'an Pan", "Wase"],
    Wase: ["Bokkos", "Kanam", "Langtang North", "Shendam"],
  },

  // RIVERS STATE
  Rivers: {
    "Port Harcourt": ["Obio/Akpor", "Eleme", "Okrika", "Oyigbo"],
    "Obio/Akpor": ["Port Harcourt", "Ikwerre", "Etche", "Oyigbo"],
    Okrika: ["Port Harcourt", "Eleme", "Ogu/Bolo"],
    "Ogu/Bolo": ["Okrika", "Eleme", "Tai"],
    Eleme: ["Port Harcourt", "Okrika", "Ogu/Bolo", "Tai", "Oyigbo"],
    Tai: ["Eleme", "Ogu/Bolo", "Gokana", "Khana"],
    Gokana: ["Tai", "Khana"],
    Khana: ["Tai", "Gokana", "Oyigbo", "Andoni", "Opobo/Nkoro"],
    Oyigbo: ["Port Harcourt", "Obio/Akpor", "Eleme", "Khana"],
    "Opobo/Nkoro": ["Khana", "Andoni"],
    Andoni: ["Khana", "Opobo/Nkoro", "Bonny"],
    Bonny: ["Andoni", "Degema"],
    Degema: ["Bonny", "Asari-Toru", "Akuku-Toru"],
    "Asari-Toru": ["Degema", "Akuku-Toru", "Abua/Odual"],
    "Akuku-Toru": ["Degema", "Asari-Toru", "Abua/Odual"],
    "Abua/Odual": ["Asari-Toru", "Akuku-Toru", "Ahoada West"],
    "Ahoada East": ["Ahoada West", "Ogba/Egbema/Ndoni"],
    "Ahoada West": ["Abua/Odual", "Ahoada East", "Ogba/Egbema/Ndoni"],
    "Ogba/Egbema/Ndoni": ["Ahoada East", "Ahoada West"],
    Emohua: ["Ikwerre", "Ahoada East", "Abua/Odual"],
    Ikwerre: ["Obio/Akpor", "Emohua", "Etche"],
    Etche: ["Obio/Akpor", "Ikwerre", "Omuma"],
    Omuma: ["Etche"],
  },

  // SOKOTO STATE
  Sokoto: {
    Binji: ["Gudu", "Silame", "Tangaza", "Sokoto North"],
    Bodinga: ["Dange Shuni", "Kware", "Shagari", "Tambuwal", "Yabo"],
    "Dange Shuni": ["Bodinga", "Kware", "Sokoto South", "Tureta", "Yabo"],
    Gada: ["Illela", "Sabon Birni", "Tangaza"],
    Goronyo: ["Gada", "Illela", "Isa", "Sabon Birni", "Wurno"],
    Gudu: ["Binji", "Tangaza"],
    Gwadabawa: ["Illela", "Kware", "Sokoto North", "Wurno"],
    Illela: ["Gada", "Goronyo", "Gwadabawa", "Wurno"],
    Isa: ["Goronyo", "Sabon Birni"],
    Kebbe: ["Shagari", "Tambuwal", "Tureta"],
    Kware: ["Bodinga", "Dange Shuni", "Gwadabawa", "Sokoto North", "Sokoto South", "Wamako"],
    Rabah: ["Binji", "Silame", "Sokoto North", "Wurno"],
    "Sabon Birni": ["Gada", "Goronyo", "Isa"],
    Shagari: ["Bodinga", "Kebbe", "Tambuwal", "Yabo"],
    Silame: ["Binji", "Rabah", "Sokoto North"],
    "Sokoto North": ["Binji", "Gwadabawa", "Kware", "Rabah", "Silame", "Sokoto South", "Wamako"],
    "Sokoto South": ["Dange Shuni", "Kware", "Sokoto North", "Wamako"],
    Tambuwal: ["Bodinga", "Kebbe", "Shagari", "Tureta", "Yabo"],
    Tangaza: ["Binji", "Gada", "Gudu"],
    Tureta: ["Dange Shuni", "Kebbe", "Tambuwal"],
    Wamako: ["Kware", "Sokoto North", "Sokoto South"],
    Wurno: ["Goronyo", "Gwadabawa", "Illela", "Rabah"],
    Yabo: ["Bodinga", "Dange Shuni", "Shagari", "Tambuwal"],
  },

  // TARABA STATE
  Taraba: {
    "Ardo Kola": ["Jalingo", "Lau", "Yorro"],
    Bali: ["Gashaka", "Gassol", "Kurmi", "Sardauna"],
    Donga: ["Gashaka", "Gassol", "Ibi", "Takum", "Ussa"],
    Gashaka: ["Bali", "Donga", "Kurmi", "Sardauna"],
    Gassol: ["Bali", "Donga", "Ibi", "Karim Lamido", "Lau"],
    Ibi: ["Donga", "Gassol", "Karim Lamido", "Wukari"],
    Jalingo: ["Ardo Kola", "Lau", "Yorro"],
    "Karim Lamido": ["Gassol", "Ibi", "Lau", "Yorro"],
    Kurmi: ["Bali", "Gashaka", "Sardauna", "Ussa"],
    Lau: ["Ardo Kola", "Gassol", "Jalingo", "Karim Lamido", "Yorro"],
    Sardauna: ["Bali", "Gashaka", "Kurmi"],
    Takum: ["Donga", "Ussa", "Wukari"],
    Ussa: ["Donga", "Kurmi", "Takum", "Wukari"],
    Wukari: ["Ibi", "Takum", "Ussa"],
    Yorro: ["Ardo Kola", "Jalingo", "Karim Lamido", "Lau"],
    Zing: ["Jalingo", "Yorro"],
  },

  // YOBE STATE
  Yobe: {
    Bade: ["Jakusko", "Karasuwa", "Nguru", "Yusufari"],
    Bursari: ["Geidam", "Tarmuwa", "Yunusari"],
    Damaturu: ["Fune", "Gujba", "Tarmuwa"],
    Fika: ["Fune", "Nangere", "Potiskum"],
    Fune: ["Damaturu", "Fika", "Gujba", "Nangere", "Potiskum", "Tarmuwa"],
    Geidam: ["Bursari", "Yunusari"],
    Gujba: ["Damaturu", "Fune", "Gulani", "Tarmuwa"],
    Gulani: ["Gujba", "Fune", "Potiskum"],
    Jakusko: ["Bade", "Karasuwa", "Nangere", "Potiskum"],
    Karasuwa: ["Bade", "Jakusko", "Machina", "Nguru", "Yusufari"],
    Machina: ["Karasuwa", "Nguru", "Yusufari"],
    Nangere: ["Fika", "Fune", "Jakusko", "Potiskum"],
    Nguru: ["Bade", "Karasuwa", "Machina", "Yusufari"],
    Potiskum: ["Fika", "Fune", "Gulani", "Jakusko", "Nangere"],
    Tarmuwa: ["Bursari", "Damaturu", "Fune", "Gujba"],
    Yunusari: ["Bursari", "Geidam", "Yusufari"],
    Yusufari: ["Bade", "Karasuwa", "Machina", "Nguru", "Yunusari"],
  },

  // ZAMFARA STATE
  Zamfara: {
    Anka: ["Bukkuyum", "Gummi", "Maru"],
    Bakura: ["Maradun", "Talata Mafara"],
    "Birnin Magaji/Kiyaw": ["Kaura Namoda", "Shinkafi", "Zurmi"],
    Bukkuyum: ["Anka", "Gummi", "Maradun", "Maru"],
    Bungudu: ["Gusau", "Maru", "Tsafe"],
    Gummi: ["Anka", "Bukkuyum", "Maradun"],
    Gusau: ["Bungudu", "Maru", "Tsafe"],
    "Kaura Namoda": ["Birnin Magaji/Kiyaw", "Shinkafi", "Talata Mafara", "Zurmi"],
    Maradun: ["Bakura", "Bukkuyum", "Gummi", "Talata Mafara"],
    Maru: ["Anka", "Bukkuyum", "Bungudu", "Gusau", "Tsafe"],
    Shinkafi: ["Birnin Magaji/Kiyaw", "Kaura Namoda", "Zurmi"],
    "Talata Mafara": ["Bakura", "Kaura Namoda", "Maradun"],
    Chafe: ["Bungudu", "Gusau", "Maru"],
    Zurmi: ["Birnin Magaji/Kiyaw", "Kaura Namoda", "Shinkafi"],
  },
}

// Function to get bordering LGAs for a given state and LGA
export function getBorderingLGAs(state: string, lga: string): string[] {
  if (NIGERIA_LGA_BORDERS[state] && NIGERIA_LGA_BORDERS[state][lga]) {
    return NIGERIA_LGA_BORDERS[state][lga]
  }

  // Return empty array if no data is available
  return []
}
